In [1]:
import numpy as np 
lst1=[1,2,3] 
array1=np.array(lst1) 
array1

array([1, 2, 3])

In [3]:
type(lst1) 

list

In [4]:
type(array1) 

numpy.ndarray

In [9]:
import numpy as np 
lst2=[4,5,6] 
array2=np.array(lst2) 
array2

array([4, 5, 6])

In [10]:
type(lst2) 

list

In [11]:
type(array2) 

numpy.ndarray

In [12]:
print("array2 multiplied by array1:",array1*array2)
print("array2 divided by array1:",array2/array1) 
print("array2 to the power of aray1:",array2**array1) 

array2 multiplied by array1: [16 25 36]
array2 divided by array1: [1. 1. 1.]
array2 to the power of aray1: [  256  3125 46656]


In [13]:

#sine function 
print("sine:" ,np.sin(array1)) 
#logarithm
print("natural logarithm:",np.log(array1))
print("base_2 logarithm:",np.log10(array1))
print("base_2 logarithm:",np.log2(array1)) 

sine: [-0.7568025  -0.95892427 -0.2794155 ]
natural logarithm: [1.38629436 1.60943791 1.79175947]
base_2 logarithm: [0.60205999 0.69897    0.77815125]
base_2 logarithm: [2.         2.32192809 2.5849625 ]


In [14]:
lst2=(3,2,1)
array2=np.array(lst2)
array2

array([3, 2, 1])

In [16]:
print("adding two numpy arrays{array1}and{array2}together:",array1+array2)

adding two numpy arrays{array1}and{array2}together: [7 7 7]


In [17]:
print(f"adding two numpy arrays{array1}and{array2}together:",array1+array2)

adding two numpy arrays[4 5 6]and[3 2 1]together: [7 7 7]
